### ISSUE TITLE
When the output bounding box is large, the generated image is incomplete.

### ISSUE THREAD

**Issue by rowantoday** [ropensci/MODIStsp#137]
When I process MODIS data in China, the generated geotiff image is incomplete and the following warning will always appear:
Warning message:
running command '"C:\OSGeo4W\bin\gdalwarp.exe" -multi -overwrite -nomd -te 73 3.5 135.5 54 -tr 0.0095050519 0.0095050519 -s_srs "+proj=sinu +lon_0=0 +x_0=0 +y_0=0 +a=6371007.181 +b=6371007.181 +units=m +no_defs" -t_srs "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0" -ot "UInt16" -r "near" -of "GTiff" -wo "INIT_DEST = NO_DATA" -wo "NUM_THREADS=2" -co "COMPRESS=None" "C:\Users\57706\AppData\Local\Temp\Rtmp0WKxH7/mstp_temp\file31dc66ba1bb2.vrt" "J:\data\MYD11A1_Aqua\download_data_8days_test\output_modistsp_resample3/Surf_Temp_8Days_1Km_v6/LST_Night_1km/MYD11A2_LST_Night_1km_2018_009.tif"' had status 1

If I narrow the output bounding box, the result is complete. This is very strange.
![q1](https://user-images.githubusercontent.com/11812896/42918390-3bc0d3ac-8b40-11e8-85ba-bec967cfc5e0.PNG)
![q2](https://user-images.githubusercontent.com/11812896/42918393-3f2d65d2-8b40-11e8-90f7-6cf1f1d45356.PNG)

**Comment by rowantoday** [comment]
my system: Windows 10. R 3.4.4

**Comment by rowantoday** [comment]
my options JSON file is as follows:
[MODIStsp_2018-07-19.zip](https://github.com/lbusett/MODIStsp/files/2208030/MODIStsp_2018-07-19.zip)

**Comment by lbusett** [comment]
Hi. Thanks for reporting this. I'll have a look as soon as possible. 

just a clarification: you mention that the result is "incomplete". Do you mean that is should cover all the "rectangle" in your image, but it only shows the upper part, right?
Also, you say that if you "narrow" the extent you get correct results, but how much do you need to reduce it? If you specify a bounding box which crosses the "complete" and "incomplete" parts do you get a complete data ? 

Lorenzo

**Comment by rowantoday** [comment]
1 Yes, the output image only contains the upper part of the "rectangle";
2 The range of whole "rectangle" is lat:[ 3.5 , 54 ],long:[ 73 , 135.5 ] , then i split the rectangle into two parts: the larger one is lat:[ 20 , 54 ],long:[ 73 , 135.5 ], the smaller on is lat:[ 3.5 , 20 ],long:[ 73 , 135.5 ]. Both parts work well. 
Now I am going to splicing the two images together by using the Mosaic tool in ArcGIS. This solution brings a limitation: in order to keep the resolution of the two images consistent, I have to specify the resolution of at least one image. This may cause one of the images to be offset by approximately 100m (for MODIS LST).

Rowantoday

**Comment by lbusett** [comment]
Seems you are experiencing something similar to ths :

https://github.com/lbusett/MODIStsp/issues/114

It is a windows specific issue i dis not manage to solve yet.

My suggestion would be to :

1) perform the processing in two blocks of tiles, but without chamging the output projection

2) join the two blocks for each date using gdal or other tools (if you want to avoid creating new files, you can create a gdal vrt file
3) reproject the mosaiced files if truly needed (i usually avoid that to prevent reprojection artifacts)

Let me know if it works.

Lorenzo

**Comment by lbusett** [comment]
Closing for now. Keeping open on #114
