### ISSUE TITLE
download failed

### ISSUE THREAD

**Issue by igianca** [ropensci/MODIStsp#138]
Dear 
I have some problems in connecting to the server for downloading, i got the following:"Request failed [403]. Retrying in 1 seconds..."
I check and I can access and download images from https://e4ftl01.cr.usgs.gov/MOLT/MOD13Q1.006/
I also had a look at the recommendations given in the issue #74 
When I run:
MODIStsp(test = 5)
I got:
"MODIStsp is running in test mode.
GDAL version in use: 2.0.1
[Thu Aug 02 16:57:07 2018] MODIStsp --> Starting processing
[Thu Aug 02 16:57:07 2018] Accessing http server at:  http://e4ftl01.cr.usgs.gov/MOTA/MCD43A3.006/
Request failed [403]. Retrying in 1 seconds..."
When I run:
GET("http://had.co.nz")
I got: "This web site has been blocked in accordance with the IT Division’s ....."
Here is the options (json):
[options.txt](https://github.com/lbusett/MODIStsp/files/2254055/options.txt)

Any suggestion on how to solve this issue?
thanks a million
best
giancarlo

**Comment by lbusett** [comment]
HI. Are you connecting to the internet through a proxy? 

Also, can you try running:

 `httr::GET("https://e4ftl01.cr.usgs.gov/MOLT/MOD13Q1.006/")`

and send me the results? 

Lorenzo

**Comment by igianca** [comment]
Hi Lorenzo
here is

> httr::GET("https://e4ftl01.cr.usgs.gov/MOLT/MOD13Q1.006/")
Response [https://e4ftl01.cr.usgs.gov/MOLT/MOD13Q1.006/]
  Date: 2018-08-06 10:44
  Status: 200
  Content-Type: text/html;charset=ISO-8859-1
  Size: 51.2 kB
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
 <head>
  <title>Index of /MOLT/MOD13Q1.006</title>
 </head>
 <body>
<pre>
********************************************************************************

                         U.S. GOVERNMENT COMPUTER
...

thanks for you support

**Comment by lbusett** [comment]
seems to be connecting properly....
  
    could you please try again with : 

`MODIStsp(test = 5)`

or 

`MODIStsp(test = 6)`

?

**Comment by igianca** [comment]
for both:
[Mon Aug 06 14:57:39 2018] MODIStsp --> Starting processing
[Mon Aug 06 14:57:39 2018] Accessing http server at:  http://e4ftl01.cr.usgs.gov/MOTA/MCD15A2H.006/
Request failed [403]. Retrying in 1 seconds...

**Comment by piyush96** [comment]
Hi Lorenzo,
I am getting something similar.

httr::GET("https://e4ftl01.cr.usgs.gov/MOLT/MOD13Q1.006/")
Error in curl::curl_fetch_memory(url, handle = handle) : 
 Failed to connect to e4ftl01.cr.usgs.gov port 443: Connection refused

Thanks 
Piyush

**Comment by lbusett** [comment]
@piyush96 

 I would try again in a few hours: LPDAAC is often on scheduled downtime on wednesdays. 

Let me know.

**Comment by Cryo2018** [comment]
Hello 
 I want to download Radiation Budget Variables-Snow Cover that is located in the "https://nsidc.org/data/mod10a1". 
I have a problem, for selected dates and tiles I face "No images available for selected area in date ...."  while in the last Friday it worked. I don't know why it doesn't work today.  

Thanks
Ali

**Comment by lbusett** [comment]
@Cryo2018 

 yes, I am noticing the same thing. Maybe something change in the way NSIDC servers handle Curl requests. I'll try to investigate. 

Lorenzo

**Comment by Cryo2018** [comment]
Thanks Lorenzo, 
 I have another problem . When I want to run Time Series 
"dataavg <- MODIStsp_extract(inrts, shpname, startdate, enddate, FUN = 'mean', na.rm = T)"   
I face this error: 
__Error in rgdal::getRasterData(con, offset = offs, region.dim = c(1, nc),  : 
  Failure during raster IO_
  I used shapefile ( point) that coordinate is same with Modis data (unnamed_ellipse_Sinusoidal).
 May I ask you help me for this problem. 

Ali

**Comment by lbusett** [comment]
@Cryo2018 

Hi Ali, 

  sorry for the late answer. I moved this on a new issue: https://github.com/ropensci/MODIStsp/issues/141

Can we continue dfiscussion there?

Lorenzo

**Comment by lbusett** [comment]
Closing for now.

@igianca and @piyush96 , please let me know if you still have problems
