### ISSUE TITLE
Running MODIStsp via ssh on a Linux server

### ISSUE THREAD

**Issue by philament** [ropensci/MODIStsp#140]
I am trying to use MODIStsp for running a large batch job on a remote Linux server while logged in via ssh, i.e. solely on the command line without access to a graphical user interface.  I am using the standalone bash/Rscript version. Unfortunately without an available X11 output, both the installation and (after successfully installing the package via X11 forwarding) the loading of MODIStsp fail due to the requirements of loading the GTK/cairoDevice, even when one is interested in only using the package from the command line entirely without GUI. This is true both for an interactive session and when calling the standalone bash/Rscript version directly from the command line without GUI. See below for an example. 

Is this a known issue? Or can MODIStsp not be used in command line-only mode logged into a server due to its dependencies on GTK? Is there a workaround other than forwarding X11 to the local host (everything works fine when doing the latter but for various reasons I'd prefer not to do that)? I imagine ideally the GTK libraries should only be loaded if the user requests the GUI and remain unloaded as long the user works on the command line.

Example of simply trying to load the package without X11 forwarding:
```
> library(MODIStsp)
R session is headless; GTK+ not initialized.

(R:13143): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()
Error: package or namespace load failed for ‘MODIStsp’:
 .onLoad failed in loadNamespace() for 'cairoDevice', details:
  call: fun(libname, pkgname)
  error: GDK display not found - please make sure X11 is running
```

Example of trying to run a saved json configuration using the standalone command line tool:
```
philipp@prod-cn-login01 - ~/temp/modistsptest                                             
>./MODIStsp.sh -g -s "modis_lst_nordic.json"                                              
/homevip/philipp/R/x86_64-pc-linux-gnu-library/3.4/MODIStsp/ExtData/Launcher              
Loading required package: MODIStsp                                                        
R session is headless; GTK+ not initialized.                                              
                                                                                          
(R:5726): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()        
Error: package or namespace load failed for ‘MODIStsp’:                                   
 .onLoad failed in loadNamespace() for 'cairoDevice', details:                            
  call: fun(libname, pkgname)                                                             
  error: GDK display not found - please make sure X11 is running                          
Loading required package: jsonlite                                                        
Loading required package: methods                                                         
Error in MODIStsp(gui = gui, options_file = options_file) :                               
  could not find function "MODIStsp"                                                      
Execution halted          
```

**Comment by lbusett** [comment]
Hi, 

  you may try looking at Issue #94, which if I remember well was quite similar. 

Let me know if it helps. 

Lorenzo

**Comment by philament** [comment]
Ah, thanks for the quick reply. Yes that appears to be exactly the same issue that I have. x2go just seems to forward the X11 output so it's similar to the workaround that I have already been using. Not ideal, but does the job, I guess. In the long run it could be useful to see if the code could be modified to only load the GTK libraries "on demand" (i.e. when people are actually launching the GUI), which should alleviate these issues for those of us who are mostly interested in command line use.

Anyways, great package! Many thanks for your efforts!

Best wishes,
Philipp

**Comment by lbusett** [comment]
Thanks for reporting this. I remember trying to solve the problem by moving all cairo/gtk related packages to "Suggests", but with no success. Apparently,  the only solution would be to completely remove them from DESCRIPTION, but in that way the package would never pass CRAN checks... 

Do you have any suggestions? 

Lorenzo

**Comment by lbusett** [comment]
Hi philipp, 

   Thanks for the suggestion.  I could fairly easily make a "companion" package without the GUI (MODIStsp_nogui) and put it on Github. Only problem is I do not know when I will have the time to do it. I'll keep you posted!

Lorenzo

**Comment by lbusett** [comment]
@philament 

If you are still interested, note that in version 2.0 we switched to a GUI based on Shiny, and also allowed to pass all processing parameters in the call to `MODIStsp`. Thus, the processing options file is no longer mandatory to run MODIStsp non interactively.
