### ISSUE TITLE
A pity: Can not download MOD44B through MODIStsp, because version 5.1 was replaced by version 6 and the version in the GUI is still version 5.1.

### ISSUE THREAD

**Issue by zhuangwearth** [ropensci/MODIStsp#143]
MOD44B v5.1 is not available at NASA lpdaac http archive (http://e4ftl01.cr.usgs.gov/molt) and was replaced by MOD44B v6. And yet, the version is still 5.1 in the GUI of MODIStsp. So MOD44B can not be download through MODIStsp. Is there any way to modify the version into 6 for MOD44B?

**Comment by lbusett** [comment]
Thanks for signalling this. Illbfix it as soon as possible (note however that i will be on vacation for yhe next 2 weeks, so it will take some time)

**Comment by zhuangwearth** [comment]
OK! Thank you for timely reply! The MODIStsp package is really very useful for MODIS product downloading and processing. Update more timely than other packages. Wish it be better!

**Comment by lbusett** [comment]
Now merged in master on github.  

library(devtools)
install_github("ropensci/MODIStsp")

Let me know if it works.
