### ISSUE TITLE
Problem with vector layer

### ISSUE THREAD

**Issue by SnehaMurmu** [ropensci/MODIStsp#148]
I have installed R 3.5.1 version and trying to download MOD 09Q1. But its showing some error which I am not able to resolve. I have attached the screenshot of my R colsole

![r_modistsp](https://user-images.githubusercontent.com/34543387/47847150-5b647580-ddf0-11e8-91e0-a5695b8e5007.PNG)

**Comment by lbusett** [comment]
Hi, 

   Which version of the `raster` package are you using? (`packageVersion("raster")`). 
If you are using v. 2.7.15, the problem may be related with https://github.com/rspatial/raster/issues/12

If tht's the case, you can try lowering the maxmemory option before running `MODIStsp` using: 

`raster::rasterOptions(maxmemory = 1e09)` 

, or installing the development version of `raster` using: 

``` r
library(devtools)
install_github("rspatial/raster")
```

**Comment by lbusett** [comment]
You need to install package `devtools` beforehand. Sorry, I forgot to mention it. 

By the way: How much RAM do you have on your PC ? 

Lorenzo

**Comment by SnehaMurmu** [comment]
I have already installed devtools as you mentioned in your reply. It has been successfully installed but the problem is now with the github. I have 4 GB RAM.

**Comment by lbusett** [comment]
Then, you have to load devtools (`library(devtools)`) before running `install_github'

**Comment by lbusett** [comment]
Also, 4GB is really low. You can therefore try also: 

raster::rasterOptions(maxmemory = 1e08)

**Comment by SnehaMurmu** [comment]
Now its working.
Thank you.

**Comment by lbusett** [comment]
Good. By the way: can you tell me what did the trick? installing `raster` or changing the memory defaults ?

**Comment by SnehaMurmu** [comment]
I just used raster::rasterOptions(maxmemory = 1e08) before running running MODIStsp. Thanks u.
