### ISSUE TITLE
Error invalid version specification

### ISSUE THREAD

**Issue by dgoodin** [ropensci/MODIStsp#155]
Attempting to run MODIStsp generated the following error:

Error: invalid version specification ‘2.6.0-nextgis-dev[2.3.1], released 2018/06/22’

System\Software\Version details are as follows:

OS: Ubuntu Linux  v. 16.04.5 LTS
R Version: 3.5.1 running in RStudio v. 1.0.143
I checked the installed dependencies listed in the installation guide for Linux and they are:

Cairo v.1.5-9
ATK v. 2.18.0-1
Pango v. 1.38.1-1
GTK+ v. 2.20.31
Glib v.2.48.2-0 Ubuntu 4.1
Curl v. 7.47
GDAL v. 2.6.0-2
Proj.4 v. 4.9.2-2

Note that the version number for Glib was listed as v. 2.8, but when I tried to update using apt-get install, 2.48 was confirmed as the most recent version. 

Any idea what the problem might be?  I checked through the list of known issues but did not see anything comparable.

Thanks!

Doug Goodin

**Comment by dgoodin** [comment]
The error occurs when I try to run using MODIStsp() from the R command line.  This is my first installation, I have not used the package prior to this. I think I updated all my packages, but I will make sure. Should I try reinstalling after I update?

**Comment by dgoodin** [comment]
I think I installed GDAL from the stable Ubuntu repository. I will try to reinstall it from some other source as suggested in the attached comment.

**Comment by dgoodin** [comment]
Update: I tried uninstalling GDAL 2.6 and installing 2.3.  This resulted in the following error:

![screenshot_2018-12-06_12-28-31](https://user-images.githubusercontent.com/27161303/49672599-43a49080-fa31-11e8-8cb2-4b66c144a10a.png)

Responding with the GdalInstallation scan didn't do anything. My next step will be to purge all GDAL files and try to start completely over.

**Comment by lbusett** [comment]
From the message, it still seems that the "nextgis 2.6.0" version is installed/present on the system. I would check your linux "sources" lists. You should make sure that you are getting GDAL from PPA:

https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable

**Comment by VjeraTurk** [comment]
If you still have trouble downgrading GDAL try [`ppa-purge`]( https://unix.stackexchange.com/questions/60595/how-to-undo-sudo-add-apt-repository/60596#60596)

    sudo ppa-purge ppa:nextgis/dev
    sudo add-apt-repository -r ppa:nextgis/dev

Then 

[Try adding ubuntugis-unstable](https://askubuntu.com/questions/1068266/how-to-get-gdal-2-0-0-on-ubuntu-16-04-lts/1103189#1103189)

    sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable

    sudo apt-get update
and install packages from it.

    sudo apt-get install libgdal-dev (...)

It worked for me but I did few more things like `apt-get upgrade` which I believe did nothing or got me step back. I kept everything I did in this [error log](https://bitbucket.org/VjeraTurk/masters-thesis/src/master/source/Error_Log_1.md) so you might want to check what I did under 5., 6. and 7.
