### ISSUE TITLE
PROJ 6 failures in MODIStsp

### ISSUE THREAD

**Issue by rsbivand** [ropensci/MODIStsp#167]
I'm testing **rgdal** and its reverse dependencies with PROJ 6 and -DACCEPT_USE_OF_DEPRECATED_PROJ_API_H. The CRS offered by PROJ >= 6 are changing, so that even though **rgdal** is still using the proj_api.h interface (for a few more months), the underlying CRS parameters are changing. Since few are using PROJ 6 yet, you have some time to fix this as **rgdal** will be built with < PROJ 6 metadata files in most cases. However, PROJ 6 was released 1 March, so you'll need to adapt. I attach my check files:

[00check.log](https://github.com/ropensci/MODIStsp/files/2951333/00check.log)
[testthat.Rout.zip](https://github.com/ropensci/MODIStsp/files/2951335/testthat.Rout.zip)

**Comment by lbusett** [comment]
@rsbivand 

Thanks for signaling this. I will have a look as soon as I can.

**Comment by rsbivand** [comment]
Issue still present with PROJ 6.1.0.

**Comment by lbusett** [comment]
@rsbivand 

    I know where the issue is, and it is easy to fix.

 Just one question, if I may: unit tests on CRAN for the current version are currently apparently ok. So, I fear that modifying the test so that it "passes" on PROJ6 would lead to failing on CRAN. How should I deal with this? Am I supposed to check for PROJ version somehow and have a "conditional" test? 

   thanks in advance, 

Lorenzo

**Comment by rsbivand** [comment]
We are aiming to start a discussion issue on github at r-spatial/discuss about this to try to offer guidance. And yes, it may well be necessary to condition on PROJ version, not least because use of project and transform methods may need installed grids as the +datum= key is removed.

**Comment by lbusett** [comment]
@rsbivand 

  thanks for the heads-up. In `MODIStsp` we use `proj` strings (sometimes even provided by the user) to drive gdal-based raster reprojection, so those changes could indeed be potentially harmful. I'm trying to build a docker with PROJ6 installed so to be able to test on the new framework. I'll use that issue to report about  problems/issues/questions, then. 

Lorenzo
