### ISSUE TITLE
Error processing MaxFRP of M*D14A1 products

### ISSUE THREAD

**Issue by bmarcos** [ropensci/MODIStsp#170]
The following error is presented when I try to process data for the M*D14A1 products, specifically when MaxFRP layer is selected:

```
Error in `[[<-`(`*tmp*`, scale_line, value = "<Scale>1</Scale>") : 
  attempt to select more than one element in vectorIndex
```

This error appears even if the option to change NA values is not selected.

I'm using MODIStsp version 1.3.8 within R version 3.6.0 on Ubuntu Linux 18.04.

**Comment by lbusett** [comment]
Hi @bmarcos 

    sorry for the late reply. Unfortunately, I am currently very busy so that I was not able to check on this issue. I'll try to do that ASAP (hopefully, by next week)

   Lorenzo

**Comment by lbusett** [comment]
@bmarcos 

  this should now be fixed on the last github version. Could you verify if it works for you? 

`remotes::install_github("ropensci/MODIStsp")`

**Comment by bmarcos** [comment]
Hi!

It is working! Thanks a lot!
