### ISSUE TITLE
Issues with extracting RasterStack

### ISSUE THREAD

**Issue by justinbeslity** [ropensci/MODIStsp#173]
I am looking to extract the pixel values for the raster stack I downloaded.

The RasterStack was successfully brought into R using the instructions.

```
ts_folder <- file.path("C:/Users/justi/OneDrive/Documents/Grad_School_Courses/Masters_Thesis/MODISTsp/Output/2016_Trial/Surf_Ref_Daily_500m_v6/Time_Series")
in_virtual_file <- file.path(ts_folder, "RData/Terra/NDVI/MOD09GA_NDVI_1_2016_32_2016_RData.RData")

ts_data   <- get(load(in_virtual_file))

ts_data

class      : RasterStack 
dimensions : 2, 4, 8, 32  (nrow, ncol, ncell, nlayers)
resolution : 463.3127, 463.3127  (x, y)
extent     : -5741834, -5739981, 4887486, 4888412  (xmin, xmax, ymin, ymax)
crs        : +proj=sinu +lon_0=0 +x_0=0 +y_0=0 +a=6371007.181 +b=6371007.181 +units=m +no_defs 
names      : MOD09GA_NDVI_2016_001, MOD09GA_NDVI_2016_002, MOD09GA_NDVI_2016_003, MOD09GA_NDVI_2016_004, MOD09GA_NDVI_2016_005, MOD09GA_NDVI_2016_006, MOD09GA_NDVI_2016_007, MOD09GA_NDVI_2016_008, MOD09GA_NDVI_2016_009, MOD09GA_NDVI_2016_010, MOD09GA_NDVI_2016_011, MOD09GA_NDVI_2016_012, MOD09GA_NDVI_2016_013, MOD09GA_NDVI_2016_014, MOD09GA_NDVI_2016_015, ... 
time        : 2016-01-01 - 2016-02-01 (range)

poly <- shapefile("C:/Users/justi/OneDrive/Documents/Grad_School_Courses/Masters_Thesis/Data/GIS_Data/Hubbard Brook Shapefiles/WS_3.shp")
> poly
class       : SpatialPolygonsDataFrame 
features    : 1 
extent      : 281374.4, 282039.9, 4870436, 4871275  (xmin, xmax, ymin, ymax)
crs         : +proj=utm +zone=19 +datum=NAD83 +units=m +no_defs +ellps=GRS80 +towgs84=0,0,0 
variables   : 4
names       :          AREA,     PERIMETER, WSHEDS0_ID,  WS 
value       : 402606.546875, 2428.60244055,          3, WS3 
```

However, when I try to extract the pixel values using MODIStsp_Extract.  I receive the error:

```
out_dataavg <- MODIStsp_extract(ts_data, poly, id_field = "AREA", 
                             small = FALSE)
Error in .local(.Object, ...) 
```

I'm not sure if this is an issue with finding the rasterstack, an error in the preprocessing, or an issue with the polygon I brought in for the extract function.

Any suggestions?  Thank you.

-Justin

**Comment by lbusett** [comment]
Hi @justinbeslity 

could you please post also the "contents" of  the `poly` object ?

**Comment by justinbeslity** [comment]
Added contents of the ```poly``` object in original comment

**Comment by lbusett** [comment]
As far as I can see, the rasterStack is very small: 2*4 pixels. Is that correct? 

Lorenzo

**Comment by justinbeslity** [comment]
Yes, that is correct.  This site is approximately 1km^2.  Eventually, I'd like to extract the complete MOIDS timeseries (full ~20 years) for roughly 30 sites of similar size.

Justin

**Comment by lbusett** [comment]
Oks. Are you sure that your shapefile is "within" the extent of the rasterStack? Did you try using option "small = TRUE"? 

Also, consider that for areas of that size maybe you would be better off using package `MODIStools` (https://ropensci.github.io/MODISTools/)

**Comment by justinbeslity** [comment]
I used the same shapefile to set the extent within the GUI.  Should I download a larger area?

I have considered using MODIStools, but the QA bits are critical to filter out the cloudy days.

-Justin

**Comment by lbusett** [comment]
Using a larger area could help, but I can not be sure.... could you try running: 

```r
raster::extract(ts_data[[1]], poly)
```

**Comment by justinbeslity** [comment]
Same error is reported.

I will try downloading a larger area and get back to you.

**Comment by lbusett** [comment]
What do you get, if you do: 

```r
raster::plot(ts_data[[1]])
```

**Comment by justinbeslity** [comment]
Same error.

However, downloading a larger area worked!  I was able to extract the timeseries data using the poly object.

**Comment by lbusett** [comment]
Good. Glad you solved this.

**Comment by justinbeslity** [comment]
I was able to extract the NDVI time series, and the data looks reasonable.

I am now having a bit of difficulty extracting the QA bits using this method.  When using the extract function I receive this error message.

```
> cirrus_xts <- MODIStsp_extract(cirrus_ts_ras, poly, id_field = "AREA", 
+                              small = TRUE)
Error in `[<-`(`*tmp*`, f, 1:ncols, value = rDT[, lapply(.SD, match.fun(FUN),  : 
  subscript out of bounds
``` 

Any thoughts?  Thank you so much for your help so far.

-Justin

**Comment by lbusett** [comment]
This is difficult to debug without the data. Would you be able to send me somehow the polygon layer and some of the single-band geotiffs?

**Comment by lbusett** [comment]
@justinbeslity

Hi.  Any updates on this? Otherwise, I'll close the issue.

**Comment by justinbeslity** [comment]
Yes I needed to use a slightly larger area to extract the pixels.  Everything seems to be working perfectly now.  Thank you for your help.
