### ISSUE TITLE
How to download hdf files in R through MODIStsp?

### ISSUE THREAD

**Issue by halima1993** [ropensci/MODIStsp#174]
I have installed MODStsp package in R, I want to know how can I directly download hdf file of land MODIS land cover v6 from NASA earthexplorer website through this package? Kindly guide me.

**Comment by lbusett** [comment]
Hi, 
  did you already try following instructions provided here? 

http://ropensci.github.io/MODIStsp/articles/interactive_execution.html

**Comment by lbusett** [comment]
Hi, 
  did you already try following instructions provided here? 

http://ropensci.github.io/MODIStsp/articles/interactive_execution.html

**Comment by lbusett** [comment]
Closed du to lack of activity. Feel free to reopen if needed.
