### ISSUE TITLE
MOD11_L2

### ISSUE THREAD

**Issue by marcopomponi** [ropensci/MODIStsp#175]
this is not quite an issue, it's a question : is it possible to download and manage MOD11_L2 data ?
it is present in the ExtData/Diff_Prodopts.xml , but they don't appear in the dropdwon list ...

![image](https://user-images.githubusercontent.com/25201975/59923359-878e3e80-9433-11e9-916a-64f9113e3218.png)

**Comment by lbusett** [comment]
Hi. MOD11L2 are SWATH products, therefore they are curtently non supported in MODIStsp. Do not know why they do appear in the file you mentioned...
