### ISSUE TITLE
Error in UseMethod("http_error") : 

### ISSUE THREAD

**Issue by haipochan** [ropensci/MODIStsp#177]
For the newest release MODIStsp 1.3.9
Download was interrupted and stopped with the following error~
-------------------
Error in UseMethod("http_error") : 
  no applicable method for 'http_error' applied to an object of class "c('simpleError', 'error', 'condition')"
-------------------

**Comment by lbusett** [comment]
Hi,

  Did this happen immediately (i. E. At the first image) or after some data was properly downloaded?

**Comment by haipochan** [comment]
Both situations happened.

First time occurred as follows:
[Wed Jul 24 13:44:04 2019] MODIStsp --> Starting processing
[Wed Jul 24 13:44:05 2019] Accessing http server at:  https://e4ftl01.cr.usgs.gov/MOLT/MOD11A2.006/
[Wed Jul 24 13:44:08 2019] Retrieving list of available ` Terra ` Files for Year 2000
Error in UseMethod("http_error") : 
  no applicable method for 'http_error' applied to an object of class "c('simpleError', 'error', 'condition')"

Second time occurred after some data was properly downloaded.

Then I switched to the older Version: 1.3.5 which is working fine.

**Comment by lbusett** [comment]
Are you able to save the options of your properties from the GUI and send me the JSON file (or cut and paste its contents here)? 

Also:  1.3.5 is quite old: why that particular version?

**Comment by haipochan** [comment]
I have another machine installed Version 1.3.5 previously. 

I have loaded from this JSON file to download. Here is the copied content (user and pwd removed)

{
  "sel_prod": "Surf_Temp_8Days_1Km (M*D11A2)",
  "sensor": "Both",
  "prod_version": "6",
  "start_date": "2000-1-1",
  "end_date": "2019-12-31",
  "bandsel": [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
  "indexes_bandsel": 0,
  "quality_bandsel": [0, 0, 0, 0, 0, 0, 0, 0],
  "start_x": 30,
  "end_x": 30,
  "start_y": 7,
  "end_y": 7,
  "user": "xxxxxxxx",
  "password": "xxxxxxxx",
  "use_aria": false,
  "download_server": "http",
  "download_range": "full",
  "proj": "User Defined",
  "output_proj4": "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0",
  "out_res_sel": "Native",
  "out_res": "Native",
  "full_ext": "Define Custom Area",
  "resampling": "near",
  "out_format": "GTiff",
  "ts_format": ["R rasterStack", "ENVI Meta", "GDAL vrt"],
  "compress": "None",
  "nodata_change": "Yes",
  "scale_val": "No",
  "delete_hdf": "No",
  "reprocess": "Yes",
  "bbox": [98.3569, 3.1387, 98.4232, 3.2021],
  "out_folder": "F:\\Sinabung Volcano Indonesia\\Sinabung-MODIS-LST",
  "out_folder_mod": "F:\\Sinabung Volcano Indonesia\\Sinabung-MODIS-LST",
  "MODIStspVersion": "1.3.3.9000",
  "custom_indexes": []
}

**Comment by lbusett** [comment]
@haipochan

Unfortunately, I was not able to replicate the issue. Could you try again, and tell me if the problem persists? 

Lorenzo

**Comment by haipochan** [comment]
Hi. Lorenzo, Thanks for your help. 

It maybe caused by the issue that GDAL does not install ogdi.dll. 

Every time when I opened the MODIStsp. it will present an error message about "gdalinfo.exe" does not start because of missing "ogdi.dll" file. Just right after closing this error message window, the MODIStsp GUI came out.

I tried to reinstall GDAL, however, the error message persists ("gdalinfo.exe" does not start because of missing "ogdi.dll" file).

**Comment by haipochan** [comment]
Hello. Lorenzo. 
I have solved the GDAL installation problem by following this instruction. 
"Installing GDAL for Windows"
https://sandbox.idre.ucla.edu/sandbox/tutorials/installing-gdal-for-windows

It seems a good choice for me (on Windows 7 SP1 x64) to install GDAL rather than using OSGeo4W network installer. No more error messages when open MODIStsp. Many thanks for your time and help!

**Comment by lbusett** [comment]
Glad you solved this!
