### ISSUE TITLE
Amount of data accessible with this pkg?

### ISSUE THREAD

**Issue by sckott** [ropensci/MODIStsp#181]
👋  as part of preparing an ropensci annual report, we're trying to estimate amount of data the various pkgs in our suite provide access to.

Do you have a sense for how much data (e.g., in GB) one can access through this pkg?  And/or whatever metric is most relevant for this data (images maybe?)?

thanks!

**Comment by lbusett** [comment]
Hi, 

    well, I'd guess the full MODIS Land Products archive would probably be in the Petabytes range. 

What I think is more relevant is that the package allows access to more than 100 products derived from MODIS imagery with global coverage, spanning a 20 years time period (2000-present) and related to different Land Surface characteristics (and therefore of interest for a wide range of applications). 

Is this sufficient? 

Lorenzo

**Comment by sckott** [comment]
thank you! Yes, that works for me
