### ISSUE TITLE
MODIS QA VI

### ISSUE THREAD

**Issue by lerouxr-dev** [ropensci/MODIStsp#184]
Hello, 
I downloaded the QA for vegetation index (VI) MOD13Q1_QA. I got 4 classes per tiles (0,1,2,3), but I can relate these value with MODIS documentation ? Any help to understand what each classe significate ? 
Regards, 
Renan

**Comment by janeuhd** [comment]
Take a look at the user guide of the data set (Section 5.5.2 QA Science data sets). In table 4 you will find the definition of the pixel reliability scores:
https://lpdaac.usgs.gov/documents/103/MOD13_User_Guide_V6.pdf

**Comment by lerouxr-dev** [comment]
Thanks for your reply. I though it was this table. The problem I got is that most of my image is marked as covered by snow or ice, or I am working under tropical area. Does it means that ice can be Ice cloud ?
Thanks

**Comment by janeuhd** [comment]
I cannot answer for your particular image, but that is surprising, I have not seen that issue in my (northern) part of the world. Usually 2 is a fairly good match to snow/ice and other extremely bright surfaces, and 3 to clouds, ocean etc. Have you checked the additional QA info (e.g. the QA_usef layer)? See table 5 in the user guide for how to interpret that layer.

**Comment by lerouxr-dev** [comment]
Here you can find wich layer I downloaded and en screen shot of the result over Brazil. Do I download the good QA ? 


![MODIStsp](https://user-images.githubusercontent.com/57791146/68943044-62b3b280-07aa-11ea-8d19-67609ba888b7.JPG)
![QA_Quality](https://user-images.githubusercontent.com/57791146/68943045-62b3b280-07aa-11ea-8187-60c4ca07a387.JPG)

**Comment by lbusett** [comment]
Hi @lerouxr-dev 

  Table 4 of the document linked by @janeuhd refers to the "Quality reliability" indicator, selectable on the left (see figure below). 

![image](https://user-images.githubusercontent.com/4480397/68945321-706c3680-07b0-11ea-923e-736e5e60bf57.png)

In MODIStsp, the "Quality Indicators" in the middle are derived by interpreting the QA bits of the Quality Layers contained in the original MODIS hdf file. The table you should look at is therefore Table 5, and not table 4. For example, the table shows that the "VI Quality" indicator that you selected is derived from bit 0-1 of the "VI quality indicators" original layer. "VI usefulness" from bits 2-5, Aerosol quantity from bits 6-7, etcetera.  

![image](https://user-images.githubusercontent.com/4480397/68945423-aad5d380-07b0-11ea-9b7c-ed5751bbebe0.png)

The interpretation is therefore in this case: 0 = Good quality, 1 = "intermediate" quality - Check other QA, 2 = Probably cloudy; 3 = NODATA for other reasons than clouds (i.e., in your case, Water pixels, apparently).  

HTH, 

   Lorenzo

**Comment by lbusett** [comment]
Closing here. Feel free to reopen if needed
