### ISSUE TITLE
Cairo --with-x11 flag removed

### ISSUE THREAD

**Issue by johannesgensheimer** [ropensci/MODIStsp#187]
Hello,

I'm trying to install the package on my MacOS system and followed the instructions in the README file.
At following point I get the error that there is no --with-x11 flag.

`2. Install the cairo library with x11 support. Enter the following into your terminal:

~$ brew uninstall --force cairo --ignore-dependencies
~$ brew cask install xquartz
~$ brew install --with-x11 cairo`

I googled it and it says something about writing own tabs. I'm not an expert at this and just want to use the tool.
Does anyone know the alternative lines to install cairo with x11?

Best and thank you,

Johannes

**Comment by lbusett** [comment]
@johannesgensheimer 

 I do not know much about MacOS, so it is difficult to help you. I however found this possible solution for installing RGtk2: 

https://yihui.org/en/2018/01/install-rgtk2-macos/

could you try using this and see if RGtk2 install2 properly? 

Lorenzo

**Comment by lbusett** [comment]
@johannesgensheimer 

did you solve this? If so, could you report how?

**Comment by johannesgensheimer** [comment]
Sorry for the late reply.
No it didn't work. I will probably not work on it for the next months but it seems to be a general problem with the x11 flag of cairo.

**Comment by lbusett** [comment]
Ok, thanks for reporting back. I'll keep this open "for reference" to other users. 
It is my plan to switch to a Shiny-based GUI to avoid these kind of problems, but I do no t know when I will have the time to do that

**Comment by lbusett** [comment]
solved in MODIStsp 2.0 - gwidgets / gtk are no longer needed due to switching to a Shiny GUI
