### ISSUE TITLE
pkgdown warning

### ISSUE THREAD

**Issue by jeroen** [ropensci/MODIStsp#188]
See: https://dev.ropensci.org/job/MODIStsp/lastBuild/console

```
Failed to parse example for topic 'install_MODIStsp_launcher' 
```

**Comment by lbusett** [comment]
Seems to be ok now. Thanks for signalling. I did not even know that the documentation was beiing mirrored on ropensci side....

**Comment by jeroen** [comment]
Thanks! Yes we announced it 6 months ago on slack and in a [blog post]( https://ropensci.org/technotes/2019/06/07/ropensci-docs/). Could you add the `https://docs.ropensci.org/MODIStsp` url to your package description file, so that people can find it from CRAN?

**Comment by lbusett** [comment]
Sure, no problem.  I already merged your PR: 
Do you see any issue in keeping both "my" and "ropensci" pages online?  
I have blog posts/various material referring to that and would not like to lose the links. 

Lorenzo

**Comment by jeroen** [comment]
We'd like as much as possible to use the docs server as the primary home for packages.

All pages in `https://ropensci.github.io/MODIStsp/...` will automatically be redirected to `https://docs.ropensci.org/MODIStsp/...`. Does that work for you?

**Comment by lbusett** [comment]
Ok, no problem at all, then! Although I am a bit sad to see my "template" gone, because I took some time in customizing it back in the day, I understand and agree with the reasoning behind this.

**Comment by jeroen** [comment]
Yes I'm sorry about that. If there are things you really liked about your template, you can propose adding them to the ropensci template: https://github.com/ropensci/rotemplate
