### ISSUE TITLE
Hi Senani,

### ISSUE THREAD

**Issue by Bhaskar02** [ropensci/MODIStsp#191]
Hi Senani, 

 glad it works ! 
tif = runGdal(product="MOD11A2",begin="2009001",end="2009001", extent=ext,SDSstring="101100",job = "MOD11A2.006") # 6.4 MB
No collection specified, getting the newest for MOD11A2 
########################
outProj          =  asIn  (if applicable, derived from Raster*/Spatial*/sf* object)
pixelSize        =  asIn  (if applicable, derived from Raster* object)
resamplingType   =  near 
Output Directory =  I:/Aerosol/Aerosol_55/MOD11A2.006 
########################
Downloading structure on 'LAADS' for: MOD11A2.006
Error in file(file, "rt") : cannot open the connection
Error in file(file, "rt") : cannot open the connection

**Comment by lbusett** [comment]
This is not the correct repo for this issue. Closing.
