### ISSUE TITLE
Output Files in default Temp location got disappear on relaunch

### ISSUE THREAD

**Issue by AD4514** [ropensci/MODIStsp#195]
When i Downloaded images after 6 hours , they downloaded in default temp folder , those files suddenly disappear when i opened R again.

**Comment by lbusett** [comment]
@AD4514 That is normal. Files in temp folder are automatically removed at each restart. If you want to keep the files, you have to select a output folder of your choice.

**Comment by AD4514** [comment]
Thank you very much for your timely response, I recovered the files using a recovery software.

**Comment by lbusett** [comment]
You're welcome! Closing here, feel free to reopen if needed.
