### ISSUE TITLE
MCD18A2 download issue.

### ISSUE THREAD

**Issue by supernitt** [ropensci/MODIStsp#198]
Hi, 
I try to download the MCD18A2 (3-hour total PAR). The later 2018 data was available. However, previous date revealed unavailable data lists. 

What is the issue? How can I fix it?

Thank you
Nitt

**Comment by lbusett** [comment]
Hi. 

   sorry, I do not understand the issue. Can you be a bit more specific about the problem? could you maybe share your processing options?

**Comment by supernitt** [comment]
Dear @lbusett ,

Thank you for your response, and sorry for unclear question.
I would like to download the 3-hour total PAR from MCD18A2 product. Then, I have a problem that the product before 2018 cannot be downloaded. I also attached images below showing the issue.

The product that I try to download. Data of 2018 and later is available. 

![image](https://user-images.githubusercontent.com/33549907/79642172-33282c80-81c6-11ea-8145-08fb006a8dba.png)

But, when I set the date before 2018, it shows like the image below.

![image](https://user-images.githubusercontent.com/33549907/79642154-1855b800-81c6-11ea-8897-4c6272088760.png)

Is there any way to fix it?

Thank you very much,
Nitt

**Comment by lbusett** [comment]
@supernitt 

  sorry for the late answer. could you please save your processing options from the GUI, open the resulting JSON file and attach here its contents? 

 Lorenzo

**Comment by supernitt** [comment]
Dear @lbusett,
Thanks for your response.
Here is my content from JSON file.

{
  "sel_prod": "Dwnwrd_PAR_3h_005dg (MCD18A2)",
  "sensor": "Combined",
  "prod_version": "6",
  "start_date": "2010-01-01",
  "end_date": "2017-12-31",
  "bandsel": [0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
  "indexes_bandsel": 0,
  "quality_bandsel": 0,
  "start_x": 27,
  "end_x": 28,
  "start_y": 7,
  "end_y": 8,
  "user": "supernitt",
  "password": "Nn19051983",
  "use_aria": false,
  "download_server": "http",
  "download_range": "full",
  "proj": "User Defined",
  "output_proj4": "+init=epsg:32648 +proj=utm +zone=48 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0",
  "out_res_sel": "Resampled",
  "out_res": "1000",
  "full_ext": "Select MODIS Tiles",
  "resampling": "near",
  "out_format": "GTiff",
  "ts_format": "R rasterStack",
  "compress": "None",
  "nodata_change": "No",
  "scale_val": "No",
  "delete_hdf": "Yes",
  "reprocess": "No",
  "bbox": ["NA", "NA", "NA", "NA"],
  "out_folder": "D:\\Work\\CMARE\\BVOCprj\\DATA\\MODIS",
  "out_folder_mod": "D:\\Work\\CMARE\\BVOCprj\\DATA\\MODIS",
  "MODIStspVersion": "1.3.9.9000",
  "custom_indexes": []
}

Thanks,
Nitt

**Comment by lbusett** [comment]
@supernitt 

   sorry for the late answer. According to here: 

https://lpdaac.usgs.gov/products/mcd18a2v006/

MCD18A2 data are available only for the 2000-2008 period (in beta state), and from 2018 onwards, so ther is unfortunately nothing we can do about this. 

Lorenzo

**Comment by supernitt** [comment]
@lbusett 

Thanks
