### ISSUE TITLE
Raster of the snow cover

### ISSUE THREAD

**Issue by Lerrtt** [ropensci/MODIStsp#200]
Hello Lorenzo,
First of all, congratulation for your MODIStsp package. I successfully installed it on PC Windows 10. I would like to use it to identify and quantify the snow cover.
In MODIStsp, select the category: Radiation budget variables - snow cover; Product: Snow_Cov_Daily_500m (M * D10_A1)
In Layers to process, I select: NDSI Snow Cover, but then I don't know what quality indicators should I select.
In image processing, how do I get the time series of the raster of the snow cover?

**Comment by lbusett** [comment]
Hi, 

     thanks for your interest in our package. Concerning your issue, it is a bit vague. I am not an expert in Snow Cover analysis, so I do not know which quality indicators are important in this case. 
I'd suggest you to have a look at the product technical documentation to better uinderstand them (you can probably find it starting from the Web page of the product, accessible from the MODISts GUI)

**Comment by lbusett** [comment]
Closing here for the moment, but feel free to reopen if you have more "focused" questions.
