### ISSUE TITLE
Accessing additional MODIS products using MODIStsp

### ISSUE THREAD

**Issue by TFyBrutalroot** [ropensci/MODIStsp#203]
I'm trying to download MODIS Evapotranspiration Anual data but there are no files in  "https://e4ftl01.cr.usgs.gov/MOLA/MYD16A3.006/" or "https://e4ftl01.cr.usgs.gov/MOLT/MOD16A3.006/" repositories. But there are ET files in "https://e4ftl01.cr.usgs.gov/MOLA/MYD16A3GF.006/" and "https://e4ftl01.cr.usgs.gov/MOLT/MOD16A3GF.006/"

Could you add this 2 other repositories in a next patch?

**Comment by ranghetti** [comment]
Sorry fot the long wait, I recently succeeded Lorenzo in maintaining this package. MOD16A3GF was added; if you still need that, please reinstall MODIStsp from GitHub with the code below and let me know if all is ok.
Thanks
```r
install.packages("remotes")
remotes::install_github("ropensci/MODIStsp")
```
