### ISSUE TITLE
Installing gWidgetsRGtk2

### ISSUE THREAD

**Issue by NAbdelatif** [ropensci/MODIStsp#208]
I can't download the package gWidgetsRGtk2 and it says not available for version 4.0.0. I have tried following the instructions with regards to downloading GTK+ but still can't get it to install. What am I doing wrong?

**Comment by lbusett** [comment]
Hi. Please have a look at issue #207

**Comment by NAbdelatif** [comment]
Hello

I have and gotten the following errors:

[cid:image002.jpg@01D6481D.411D9EC0]

I’ve tried following all different suggestions, but no luck!

**Comment by lbusett** [comment]
HI. I do not see the image, sorry.

**Comment by NAbdelatif** [comment]
Sorry, and now? 
![gwidgetsrkt2](https://user-images.githubusercontent.com/66787762/85264887-b0e01100-b471-11ea-9bd5-6f462e06c02f.PNG)

**Comment by lbusett** [comment]
I don't know, really. I still did not make the switch to R4.0. 

Did you already install the proper version of RTools? 

Lorenzo

**Comment by lbusett** [comment]
https://cran.r-project.org/bin/windows/Rtools/

**Comment by NAbdelatif** [comment]
Hi Lorenzo, it took a bit of fiddling around but managed to get it to work, thank you for your help!

**Comment by khalilT** [comment]
Hello @NAbdelatif, I am facing the same problem as you, it didn't work even after installing Rtools.
Can you please tell me how you fixed this?

**Comment by lbusett** [comment]
@NAbdelatif 

  I have different users apparantly suffering from this issue. Could you explain how you did solve it? 

Thanks in advance, 

Lorenzo

**Comment by khalilT** [comment]
Hi,

I actually managed to find a solution.
Rtools needs to be installed, and then, I downloaded the binary file for the [gWidgetsRGtk2 ](http://ftp.uni-bayreuth.de/math/statlib/R/CRAN/src/contrib/Descriptions/gWidgetsRGtk2.html), and installed the package offline, and it worked !

cheers,

Khalil

**Comment by NAbdelatif** [comment]
@khalilT @lbusett apologies for the late response! Glad you got it to work eventually. 

My problem was the path and what helped me were the following instructions [http://yizhexu.com/2017/02/r-path/](url).

**Comment by lbusett** [comment]
@khalilT 

thanks!

@NAbdelatif 

thanks for answering back. One question: This was needed for RTools to work properly ?

**Comment by NAbdelatif** [comment]
Hello, yes it is and will also allow you to download gWidgetsRGtk2 with no problems!

**Comment by myzhenghr** [comment]
> Hi,
> 
> I actually managed to find a solution.
> Rtools needs to be installed, and then, I downloaded the binary file for the [gWidgetsRGtk2 ](http://ftp.uni-bayreuth.de/math/statlib/R/CRAN/src/contrib/Descriptions/gWidgetsRGtk2.html), and installed the package offline, and it worked !
> 
> I found the solution in this forum here: http://forum.bebac.at/mix_entry.php?id=21564
> see the last posts.
> 
> cheers,
> 
> Khalil

Hi Khalil
Could you pleae send me a copy of the gWidgetsRGtk2 binary file? I just send the accessing request to the owner of the Google Drive, but i need it urgently and can't wait anymore. My email address is myzhenghrsc@gmail.com. 
Thanks in advance,
Henry

**Comment by lbusett** [comment]
Hi all ,

    in the new version of MODIStsp the gwidgets GUI has been replaced by a new onre based oon shiny, so installing gWidgets/gWidgetsRgtk2 won't be a problem anymore. Closing here.
