### ISSUE TITLE
object 'nodata_in_tmp' not found

### ISSUE THREAD

**Issue by dkhramov** [ropensci/MODIStsp#213]
Hi @lbusett

Thanks for 2.0 update! I wanted to calculate NDVI using scaling but without modifying NoData values and got the error:

Error in split_nodata_values(nodata_in_tmp) :
  object 'nodata_in_tmp' not found
MODIStsp ... MODIStsp_process_bands -> split_nodata_values -> strsplit

With "nodata_change" and  "scale_val" both true or false all works.

Part of my options file:

{
  "selcat": "Radiation Budget Variables - Land Surface Reflectance",
  "selprod": "Surf_Ref_8Days_250m (M*D09Q1)",
  "prod_version": "6",
  "sensor": "Terra",
  "bandsel": null,
  "quality_bandsel": ["state_mod35_snow", "state_land_wat", "state_cld_shd", "state_cld"],
  "indexes_bandsel": ["NDVI", "SAVI"],
   ...
  "out_projsel": "User Defined",
  "output_proj": "4326",
  "out_res_sel": "Native",
  "out_res": 231.6564,
  "resampling": "near",
  "reprocess": false,
  "delete_hdf": false,
  "nodata_change": false,
  "scale_val": true,
  "out_format": "GTiff",
   ...
  "MODIStspVersion": "2.0.2"
}

OS: Windows 10

**Comment by lbusett** [comment]
Thanks for reporting, I'll have a look ASAP.

Lorenzo

**Comment by lbusett** [comment]
This should now be fixed - stupid mistake (<- instead of ==) 

@dkhramov :  could you check by reinstalling from github

**Comment by dkhramov** [comment]
I've reinstalled the library. Everything works fine. Thank you!
