### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by Cassie-Qiu68** [ropensci/MODIStsp#214]
Hi @karthik ,

I am very insterested in the MODIStsp package and I am trying to install the package, however, it always failed and error says: 
"Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'raster' 3.1-5 is already loaded, but >= 3.3.13 is required"
In fact, I have updated the raster package.

When I try to use github to install, error also occured as:
"Error: Failed to install 'unknown package' from GitHub:
  Send failure: Connection was reset"

My system is Window 10.
Looking forward to your kind help, thanks advance!

**Comment by lbusett** [comment]
hi @Cassie-Qiu68 

For problem 1) try reinstalling the `raster` package on a fresh R session
For problem 2), what command are you issuing, when trying to install from github ? 

Lorenzo

**Comment by Cassie-Qiu68** [comment]
Hi @lbusett 

Many thanks for you help. I have solve the problem and install it successfully.
I guess the failure was caused by the version of R. Although I re-installed the [raster](url) several times, the version is not the newest. After I update the R from 3.5.2 to the 4.0.2, the update for [raster](url) package is successful. 

Sijing
