### ISSUE TITLE
Cannot accept output folder in MODIStsp GUI

### ISSUE THREAD

**Issue by mhkhan81** [ropensci/MODIStsp#215]
Hi
I went through newly developed MODIStsp GUI found it very user friendly. But I come across an issue. I want to download multi-temporal ET data from MOD16A2 product. I have provide all the required information in MODIStsp GUI. but when finally come to browse the output folder for the downloaded and process data. the Browse doesn't accept the folder name. Further when I Run MODIStsp I got this following message in R console 

Warning: Error in : $ operator is invalid for atomic vectors
  74: observeEventHandler [C:/Users/mhkhan/Documents/R/win-library/3.6/MODIStsp/app/srv/mstp_prds_srv.R#225]
   3: shiny::runApp
   2: MODIStsp_GUI
   1: MODIStsp

Could you please advise how to solve the issue.

Thanks 

Khan

**Comment by lbusett** [comment]
Hi @mhkhan81 

 could you explain a bit more what happens when you click the browse button? Does the windows allowing to select the folder 
appear? If so, what happens when you try to select a folder? Also, could you share the results of

``` r
devtools::session_info()
```

Lorenzo

**Comment by mhkhan81** [comment]
The devtools::session_info() is as under

Session info
---------------------------------------------------------------------------------------------------------------------
 setting  value
 version  R version 3.6.0 (2019-04-26)
 os       Windows >= 8 x64
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_New Zealand.1252
 ctype    English_New Zealand.1252
 tz       Pacific/Auckland
 date     2020-09-18

- Packages
-------------------------------------------------------------------------------------------------------------------------
 package        * version date       lib source
 assertthat       0.2.1   2019-03-21 [1] CRAN (R 3.6.0)
 backports        1.1.9   2020-08-24 [1] CRAN (R 3.6.3)
 base64enc        0.1-3   2015-07-28 [1] CRAN (R 3.6.0)
 bitops           1.0-6   2013-08-17 [1] CRAN (R 3.6.0)
 callr            3.4.4   2020-09-07 [1] CRAN (R 3.6.3)
 class            7.3-17  2020-04-26 [1] CRAN (R 3.6.3)
 classInt         0.4-3   2020-04-07 [1] CRAN (R 3.6.3)
 cli              2.0.2   2020-02-28 [1] CRAN (R 3.6.3)
 codetools        0.2-16  2018-12-24 [2] CRAN (R 3.6.0)
 crayon           1.3.4   2017-09-16 [1] CRAN (R 3.6.0)
 crosstalk        1.1.0.1 2020-03-13 [1] CRAN (R 3.6.3)
 data.table       1.13.0  2020-07-24 [1] CRAN (R 3.6.3)
 DBI              1.1.0   2019-12-15 [1] CRAN (R 3.6.3)
 desc             1.2.0   2018-05-01 [1] CRAN (R 3.6.3)
 devtools         2.3.1   2020-07-21 [1] CRAN (R 3.6.3)
 digest           0.6.25  2020-02-23 [1] CRAN (R 3.6.3)
 dplyr            1.0.2   2020-08-18 [1] CRAN (R 3.6.3)
 e1071            1.7-3   2019-11-26 [1] CRAN (R 3.6.3)
 ellipsis         0.3.1   2020-05-15 [1] CRAN (R 3.6.3)
 fansi            0.4.1   2020-01-08 [1] CRAN (R 3.6.3)
 fastmap          1.0.1   2019-10-08 [1] CRAN (R 3.6.3)
 fs               1.5.0   2020-07-31 [1] CRAN (R 3.6.3)
 gdalUtilities    1.1.1   2020-07-25 [1] CRAN (R 3.6.3)
 generics         0.0.2   2018-11-29 [1] CRAN (R 3.6.3)
 glue             1.4.2   2020-08-27 [1] CRAN (R 3.6.3)
 htmltools        0.5.0   2020-06-16 [1] CRAN (R 3.6.3)
 htmlwidgets      1.5.1   2019-10-08 [1] CRAN (R 3.6.3)
 httpuv           1.5.4   2020-06-06 [1] CRAN (R 3.6.3)
 httr             1.4.2   2020-07-20 [1] CRAN (R 3.6.3)
 jsonlite         1.7.1   2020-09-07 [1] CRAN (R 3.6.3)
 KernSmooth       2.23-17 2020-04-26 [1] CRAN (R 3.6.3)
 later            1.1.0.1 2020-06-05 [1] CRAN (R 3.6.3)
 lattice          0.20-41 2020-04-02 [1] CRAN (R 3.6.3)
 leafem           0.1.3   2020-07-26 [1] CRAN (R 3.6.3)
 leaflet          2.0.3   2019-11-16 [1] CRAN (R 3.6.3)
 lifecycle        0.2.0   2020-03-06 [1] CRAN (R 3.6.3)
 magrittr         1.5     2014-11-22 [1] CRAN (R 3.6.3)
 mapedit          0.6.0   2020-02-02 [1] CRAN (R 3.6.3)
 memoise          1.1.0   2017-04-21 [1] CRAN (R 3.6.3)
 mime             0.9     2020-02-04 [1] CRAN (R 3.6.2)
 MODIStsp       * 2.0.2   2020-09-15 [1] Github (ropensci/MODIStsp@88de3ec)
 pillar           1.4.6   2020-07-10 [1] CRAN (R 3.6.3)
 pkgbuild         1.1.0   2020-07-13 [1] CRAN (R 3.6.3)
 pkgconfig        2.0.3   2019-09-22 [1] CRAN (R 3.6.3)
 pkgload          1.1.0   2020-05-29 [1] CRAN (R 3.6.3)
 png              0.1-7   2013-12-03 [1] CRAN (R 3.6.0)
 prettyunits      1.1.1   2020-01-24 [1] CRAN (R 3.6.3)
 processx         3.4.4   2020-09-03 [1] CRAN (R 3.6.3)
 promises         1.1.1   2020-06-09 [1] CRAN (R 3.6.3)
 ps               1.3.4   2020-08-11 [1] CRAN (R 3.6.3)
 purrr            0.3.4   2020-04-17 [1] CRAN (R 3.6.3)
 R6               2.4.1   2019-11-12 [1] CRAN (R 3.6.3)
 rappdirs         0.3.1   2016-03-28 [1] CRAN (R 3.6.3)
 raster           3.3-13  2020-07-17 [1] CRAN (R 3.6.3)
 Rcpp             1.0.5   2020-07-06 [1] CRAN (R 3.6.3)
 remotes          2.2.0   2020-07-21 [1] CRAN (R 3.6.3)
 rlang            0.4.7   2020-07-09 [1] CRAN (R 3.6.3)
 rprojroot        1.3-2   2018-01-03 [1] CRAN (R 3.6.3)
 rstudioapi       0.11    2020-02-07 [1] CRAN (R 3.6.3)
 sessioninfo      1.1.1   2018-11-05 [1] CRAN (R 3.6.3)
 sf               0.9-5   2020-07-14 [1] CRAN (R 3.6.3)
 shiny          * 1.5.0   2020-06-23 [1] CRAN (R 3.6.3)
 shinyalert       2.0.0   2020-09-12 [1] CRAN (R 3.6.3)
 shinydashboard   0.7.1   2018-10-17 [1] CRAN (R 3.6.3)
 shinyFiles       0.8.0   2020-04-14 [1] CRAN (R 3.6.3)
 shinyjs          2.0.0   2020-09-09 [1] CRAN (R 3.6.3)
 sp               1.4-2   2020-05-20 [1] CRAN (R 3.6.3)
 stringi          1.4.6   2020-02-17 [1] CRAN (R 3.6.2)
 stringr          1.4.0   2019-02-10 [1] CRAN (R 3.6.1)
 testthat         2.3.2   2020-03-02 [1] CRAN (R 3.6.3)
 tibble           3.0.3   2020-07-10 [1] CRAN (R 3.6.3)
 tidyselect       1.1.0   2020-05-11 [1] CRAN (R 3.6.3)
 units            0.6-7   2020-06-13 [1] CRAN (R 3.6.3)
 usethis          1.6.1   2020-04-29 [1] CRAN (R 3.6.3)
 uuid             0.1-4   2020-02-26 [1] CRAN (R 3.6.3)
 vctrs            0.3.4   2020-08-29 [1] CRAN (R 3.6.3)
 withr            2.2.0   2020-04-20 [1] CRAN (R 3.6.3)
 xml2             1.3.2   2020-04-23 [1] CRAN (R 3.6.3)
 xtable           1.8-4   2019-04-21 [1] CRAN (R 3.6.3)
 xts              0.12.1  2020-09-09 [1] CRAN (R 3.6.3)
 yaml             2.2.1   2020-02-01 [1] CRAN (R 3.6.3)
 zoo              1.8-8   2020-05-02 [1] CRAN (R 3.6.3)

[1] C:/Users/mhkhan/Documents/R/win-library/3.6
[2] C:/Program Files/R/R-3.6.0/library

**Comment by mhkhan81** [comment]
Hi Lorenzo

Thanks for your email. 
The browse for attaching the folder path is blocked when moving the cursor to the record line; it shows a red circle with a line inside, which means cannot upload.
After being unable to define the output folder. when run the MODItsp it give me the following result in R console:
Warning: Error in : $ operator is invalid for atomic vectors
  **_74: observeEventHandler [C:/Users/mhkhan/Documents/R/win-library/3.6/MODIStsp/app/srv/mstp_prds_srv.R#225]
   3: shiny::runApp
   2: MODIStsp_GUI
   1: MODIStsp**_

I will really appreciate if you could help me in extracting the MOD16A2 ET data. 

Regards

Hamed

**Comment by lbusett** [comment]
@mhkhan81 

Actually, to select the folder, you have to click on the "browse" buttons, and select it from the shinyFiles interface. Did you already try that? 

Lorenzo

**Comment by mhkhan81** [comment]
Yes I tried that but still is not working. By clicking the browse button no
change occurs.

**Comment by lbusett** [comment]
Clicking the button should open a window like this one: 

![image](https://user-images.githubusercontent.com/4480397/93584119-268e4700-f9a5-11ea-935f-38bfb034fabb.png)

If it is not happening, of course you can not select the folder!

**Comment by mhkhan81** [comment]
What is the issue behind this?

**Comment by lbusett** [comment]
I have no clue, sorry... apparently, all your packages are up-to-date so it should be working... 
What browser are you using ?

**Comment by mhkhan81** [comment]
When I run the MODIStsp library in R, the GUI automatically starts in
Internet explorer.
 I am using Internet explorer 11.

**Comment by lbusett** [comment]
It may be an issue with Internet Explorer. I only tested on Chrome. 
Would you be willing to try to install chrome and set it as your default browser to test ?

**Comment by mhkhan81** [comment]
I am also using Chrome and its my default browser but MODIStsp goes to
internet explorer.

**Comment by mhkhan81** [comment]
With change of browser it works Now. Now i can browse the output folder. By
running the GUI Nothing happen yet. My output folder is still empty.

**Comment by lbusett** [comment]
That's strange - it should go to the default browser....

I'll try to send you some code later to test if the problem is with shinyfiles/IE interaction.

**Comment by mhkhan81** [comment]
In chrome I can browse the output folder, that problem is solved. But when
clicking on the RUN MODIStsp button the GUI closed and the same few lines
came in R console. No download or process happens in the output folder or
in the R console.

**Comment by lbusett** [comment]
That is probably due to the fact that you did not select all processing options - I will soon post an update that will tell the user which specific inputs are missing / wrong.

**Comment by mhkhan81** [comment]
Yes you were right as I was only selecting ET. But now after selecting all
the options in the given selectors and it works.
I really appreciate your prompt response and help.
