### ISSUE TITLE
Timeout issue downloading MODIS tiles

### ISSUE THREAD

**Issue by micha-silver** [ropensci/MODIStsp#217]
Similar to https://github.com/ropensci/MODIStsp/issues/74#issue-229199298, I am experiencing repeated timeouts over the past week or so.  
```
Error in curl::curl_fetch_memory(url, handle = handle): Timeout was reached: [e4ftl01.cr.usgs.gov] Connection timed out after 10001 milliseconds
Request failed [ERROR]. Retrying in 2.6 seconds...
Error in curl::curl_fetch_memory(url, handle = handle): Timeout was reached: [e4ftl01.cr.usgs.gov] Connection timed out after 10001 milliseconds
Request failed [ERROR]. Retrying in 1.6 seconds...
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [e4ftl01.cr.usgs.gov] Connection timed out after 10001 milliseconds
Error: [Tue Sep 29 15:29:09 2020] Error: http server seems to be down! Please try again later. Aborting!
```
Has anyone else seen this? On some days the download goes fine for several hours, then just disconnects, and all attempts to rerun MODIStsp() just timeout.

When this happens, I cannot even browse to: https://e4ftl01.cr.usgs.gov/MOLT/MOD11A1.006/2000.03.03/ 

Thanks

**Comment by lbusett** [comment]
This usually happens due to schduled downtimes of the NASA DAAC servers, usually scheduled on wednesdays. 

In these cases, you'll just have to wait until the servers are back up. 

Lorenzo

**Comment by micha-silver** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Thanks,
    I followed your responses to similar posts about
        the downtime on Wednesdays. In my case the slow downloads
        continued over the weekend. Then the download actually "opened
        up" and started to flow freely on Tuesday,Wednesday and
        Thursday! Maybe they changed their scheduled downtimes?
    
      
    Best Regards, and thanks for this excellent
        package,
    Micha
    
    
    On 02/10/2020 13:49, Lorenzo Busetto
      wrote:
    
    
      
      This usually happens due to schduled downtimes of the NASA DAAC
        servers, usually scheduled on wednesdays.
      In these cases, you'll just have to wait until the servers are
        back up.
      Lorenzo
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ropensci/MODIStsp/issues/217#issuecomment-702663225",
"url": "https://github.com/ropensci/MODIStsp/issues/217#issuecomment-702663225",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    -- 
Micha Silver
Arava Drainage Authority
cell: +972-523-665918

**Comment by hubert-thieriot** [comment]
Facing the same issue. I found out that extending httr timeout to 20 seconds solves it most of the time. Will submit a PR soon.
