### ISSUE TITLE
Package has been removed from CRAN

### ISSUE THREAD

**Issue by gitschneider** [ropensci/MODIStsp#218]
I was not able to install MODIStsp via `install.packages` as stated in the docs. Output:

```
install.packages("MODIStsp")
Installing package into '/usr/lib/R/site-library'
(as 'lib' is unspecified)
Warning message:
package 'MODIStsp' is not available (for R version 4.0.2) 
```

When checking the CRAN page of this package (https://cran.r-project.org/package=MODIStsp), I got this message:

```
Package ‘MODIStsp’ was removed from the CRAN repository.

Formerly available versions can be obtained from the archive.

Archived on 2020-10-07 for policy violation.

The most recent check results can be obtained from the check results archive.
```

Thank you in advance for your work.

**Comment by lbusett** [comment]
@gitschneider 

Thanks for reporting this. Unfortunately I had a problem in the last submission  that I was not able to fix in time to avoid archiving. 
Now the package is on its way to CRAN again and hopefully it will be online soon. 

In the meantime, you could install it from github. 

  Lorenzo
