### ISSUE TITLE
error when processing existing modis hdf files

### ISSUE THREAD

**Issue by Thandi1509** [ropensci/MODIStsp#229]
Hi, I was able to install MODIStsp. However when I run the GUI to process existing HDFs (to convert to TIFF), I get the error below. I would appreciate any help. Thank you for developing this!

GDAL version in use: 3.0.4
Loading required package: shiny

Listening on http://127.0.0.1:5236
Warning in sf::st_is_longlat(x) :
  bounding box has potentially an invalid value range for longlat data
[Wed Jan 13 11:41:46 2021] MODIStsp --> Starting processing
[Wed Jan 13 11:41:46 2021] Accessing http server at:  https://e4ftl01.cr.usgs.gov/MOLT/MOD11C1.006/
[Wed Jan 13 11:41:46 2021] Retrieving list of available ` Terra ` Files for Year 2019
[Wed Jan 13 11:41:46 2021] HDF File: MOD11C1.A2019001.006.2019009081044.hdf already exists on your system. Skipping download!
[Wed Jan 13 11:41:46 2021] [Wed Jan 13 11:41:46 2021] 1 files for date: 2019.01.01 were successfully downloaded!
[Wed Jan 13 11:41:46 2021] Processing Terra LST_Day_CMG files for date: 2019_01_01
Warning: Error in h: error in evaluating the argument 'x' in selecting a method for function 'res': Cannot create RasterLayer object from this file; perhaps you need to install rgdal first
  74: observeEventHandler [C:/Users/tkapwata/OneDrive - South African Medical Research Council/Documents/R/win-library/4.0/MODIStsp/app/srv/mstp_prds_srv.R#232]
   3: shiny::runApp
   2: MODIStsp_GUI
   1: MODIStsp

**Comment by ranghetti** [comment]
The error is self-explaining: `perhaps you need to install rgdal first`.

If instead `rgdal` is installed, to deepen your case I need to be able to reproduce it. When you opened this issue you should have noticed (and deleted) a template, which was written for a reason. Please fill that template with all the required information, so I will be able to debug it.

**Comment by Thandi1509** [comment]
Thanks for the quick response. I am a new user to this platform and did not notice the template - apologies. I was able to get it to run.
