### ISSUE TITLE
KNDVI (expression)  - MODIStsp

### ISSUE THREAD

**Issue by Olive-r** [ropensci/MODIStsp#233]
Hello,

Can the new KNDVI * be applied BY by using MODIStsp?

If yes, how should the expression be applied?

Thanks.

Oli

* This is the new KNDVI: 

G. Camps‑Valls, M. Campos‑Taberner, Á. Moreno‑Martínez, S. Walther, G. Duveiller, A. Cescatti, M. D. Mahecha, J. Muñoz‑Marí, F. J. García‑Haro, L. Guanter, M. Jung, J. A. Gamon, M. Reichstein, S. W. Running, A unified vegetation index for quantifying the terrestrial biosphere. Sci. Adv. 7, eabc7447 (2021). doi: 10.1126/sciadv.abc7447

**Comment by ranghetti** [comment]
Hello,
you can add it as new index: open the MODIStsp GUI with `MODIStsp()`, then click on the "Add New Spectral Index" button (bottom of the first sheet) and add the index related information:
![Screenshot_20210305_161050](https://user-images.githubusercontent.com/6874239/110134663-ee04ed00-7dcd-11eb-99aa-9374cd3fc7b9.png)

**Comment by ranghetti** [comment]
Ps: please notice that I wrote the formula as an example, following the statement "A reasonable choice is taking the average value σ = 0.5(NIR + red)". Cange the formula accordingly to your needings.

**Comment by Olive-r** [comment]
Thank you very much Luigi! 

I had several doubts to formulate the expression by using Modis, and precisely one of them was the sigma parameter. The authors recommend σ=0.5, but the code illustrated as an example in the supplementary material shows σ=1.
You are right. The authors go into more detail about sigma in the supplementary material: https://advances.sciencemag.org/content/suppl/2021/02/22/7.9.eabc7447.DC1/abc7447_SM.pdf

Thanks for everything. This R package is fantastic.
 
Oli
