### ISSUE TITLE
M*D17A3H server change

### ISSUE THREAD

**Issue by bhanberry** [ropensci/MODIStsp#237]
**Issue description**

The server for Net_PP_Yearly_500m now is https://e4ftl01.cr.usgs.gov/MOLT/MOD17A2HGF.061/ updated from https://e4ftl01.cr.usgs.gov/MOLT/MOD17A3H.006/ 

**Reproducible example**

[Tue Jul 06 19:51:59 2021] MODIStsp --> Starting processing
[Tue Jul 06 19:51:59 2021] Accessing http server at:  https://e4ftl01.cr.usgs.gov/MOLT/MOD17A3H.006/
Request failed [404]. Retrying in 1 seconds...
Request failed [404]. Retrying in 1 seconds...
Request failed [404]. Retrying in 1 seconds...
Request failed [404]. Retrying in 1.1 seconds...
Error: [Tue Jul 06 19:52:04 2021] Error: http server seems to be down! Please try again later. Aborting!
```r
## PLEASE DELETE AND WRITE YOUR OWN
library(MODIStsp)
MODIStsp(gui = FALSE, opts_file = "/path/of/the/parameter_file.json")
# file parameter_file.json _must_ be attached or copied as text,
# as well as referenced files (e.g. spafile)
```

**Expected and actual behavior**

```
## PASTE HERE THE OUTPUT OF YOUR EXAMPLE CODE
```

**System information**

```
# PASTE HERE YOUR OUTPUT
```

**Additional context**

**Scientific publication**

**Comment by ranghetti** [comment]
Product M*D17A3H was removed due to its unavailability, and replaced with M*D17A3HGF (version 6). M*D17A2HGF was also added. Please install the develop branch of the package, try it and provide me a feedback.
```r
install.packages("remotes")
remotes::install_github("ropensci/MODIStsp", ref = "devel")
```

**Comment by bhanberry** [comment]
Thank you! It is working.

Not sure if it is related, but a password error occurred even though I could log in at Earthdata. I changed my password and then no error.

Thanks again, Brice
