### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by hgbzzw** [ropensci/MODIStsp#241]
when I use MODIStsp to download MOD11A1 land surface temperature(LST) data. It showed this issue:
[Mon Aug 02 16:04:33 2021] MODIStsp --> Starting processing
[Mon Aug 02 16:04:33 2021] Accessing http server at:  https://e4ftl01.cr.usgs.gov/MOLT/MOD11A1.006/
Error in curl::curl_fetch_memory(url, handle = handle): Timeout was reached: [e4ftl01.cr.usgs.gov] Connection timed out after 10013 milliseconds
Request failed [ERROR]. Retrying in 1 seconds...
Error in curl::curl_fetch_memory(url, handle = handle): Timeout was reached: [e4ftl01.cr.usgs.gov] Connection timed out after 10002 milliseconds
Request failed [ERROR]. Retrying in 1 seconds...
Error in curl::curl_fetch_memory(url, handle = handle): Timeout was reached: [e4ftl01.cr.usgs.gov] Connection timed out after 10002 milliseconds
Request failed [ERROR]. Retrying in 1 seconds...
Error in curl::curl_fetch_memory(url, handle = handle): Timeout was reached: [e4ftl01.cr.usgs.gov] Connection timed out after 10010 milliseconds
Request failed [ERROR]. Retrying in 1 seconds...
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [e4ftl01.cr.usgs.gov] Connection timed out after 10002 milliseconds
Warning: Error in : [Mon Aug 02 16:05:27 2021] Error: http server seems to be down! Please try again later. Aborting!
  3: shiny::runApp
  2: MODIStsp_GUI
  1: MODIStsp
however, I can open the website of https://e4ftl01.cr.usgs.gov/MOLT/MOD11A1.006/ in google chrome and check the data in this HTTP server.I do not know why it does not work?

by the way, I used v2aryN as my PC proxy in Win 10, can it affect MODIStsp work?
waiting for your early reply! Thanks a lot!

**Comment by ranghetti** [comment]
I cannot investigate your problem, since you did not provide a reproducible example. Please reopen a new issue **strictly following** the indications provided in the issue template (choose "Help needed / question" and provide the required information).
